version: '3'
volumes: 
    records:
networks: 
    database:
    frontend:
    queue:
services: 
    database:
        image: postgres:12.1
        volumes:
            # Data volume 
            - records:/var/lib/postgresql/data
            # Scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - database
    frontend:
        image: nginx:1.16.1
        volumes:
            # Frontend 
            - ./frontend:/usr/share/nginx/html
            # Reverse proxy config
            - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 80:80
        networks: 
            - frontend
        depends_on: 
            - app
    app:
        image: python:3.8.1
        volumes:
            # Application
            - ./backend/app:/backend/app
        working_dir: /backend/app
        command: bash ./run.sh
        networks: 
            - database
            - frontend
            - queue
        depends_on: 
            - database
            - queue
    queue:
        image: redis:5.0.7
        networks: 
            - queue
    worker:
        build: backend/worker
        volumes: 
            # Worker
            - ./backend/worker:/backend/worker
        working_dir: /backend/worker
        command: worker.py
        networks: 
            - queue
        depends_on: 
            - queue